[build]
  command = "npm run build && npx https://gist.github.com/AnandChowdhary/bf1dce1400a6fc86afd1921085feff93 https://raw.githubusercontent.com/TwenteMe/data/master/redirects.json && cp _redirects public/_redirects"
  publish = "public"
